### ISSUE TITLE
Unable to resolve IP addresses from local DNS in Active Directory

### ISSUE THREAD

**Issue by robert-todora** [robert-todora/snafflepy#9]
Need some guidance getting a list of computers from Active Directory and taking their domain names and resolving them to IPs so the SMB login can be attempted.

**Comment by Auto19** [comment]
Good project to checkout for this: https://github.com/dirkjanm/adidnsdump
Also, dnslib has structures for DNS types

https://github.com/Auto19/ADHunt/blob/main/adhunt.py#L249-L347
This is how I am requesting all of the DNS records from AD in ADHunt.

You can then iterate through these records, specifically A and AAAA records to get ips (PTR too probably).

The other method is to get computers that have a dnshostname.
 
The methods are both used below:
https://github.com/Auto19/ADHunt/blob/main/adhunt.py#L468-L509

If you choose method 2 you have to have a namerserver to resolve the hostnames you found.  I do this by iterating through all the dns records and adding ns to a dnsresolver. 
https://github.com/Auto19/ADHunt/blob/main/adhunt.py#L355-L393

Using both methods gives the most coverage but you probably only need to iterate A, AAAA, and PTR records for the first part.
